apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

configMapGenerator:
  - name: test-dependent
    options:
      disableNameSuffixHash: true
    literals:
      - key=value
