apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      caProvider:
        type: ConfigMap
        name: vault-ca
        namespace: external-secrets
        key: ca.crt
      server: 'https://10.16.50.14:8200'
      path: 'secret'
      auth:
        kubernetes:
          mountPath: hub
          role: hub-role
          serviceAccountRef:
            name: cluster-external-secrets
            namespace: external-secrets
