apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: 'https://10.16.50.14:8200'
      path: 'secret'
      auth:
        kubernetes:
          mountPath: kubernetes
          role: hub
          serviceAccountRef:
            name: cluster-external-secrets
            namespace: external-secrets
