apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog.git/external-secrets-operator/instance/base

secretGenerator:
  - name: vault
    namespace: default
    options:
      disableNameSuffixHash: true
    literals:
      - token=test
